<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
		'Product' => '产品介绍',
		'workstation' => '移动红外工作站',
		'kc100' => 'KC100红外热成像仪',
		'kc500' => 'KC500红外热成像仪',
		'kc700' => 'KC700红外热成像仪',
		'kc800' => 'KC800红外热成像仪',
		'kc850' => 'KC850红外热成像仪',
		'gl600' => 'GL600 SF6气体红外检漏仪',
		'carmobile' => '车载移动检测系统',
		'substation' => '变电站红外监测系统',
		'helicopter' => '直升机巡检系统',
		'workstation_s' => '移动红外工作站',
		'kc100_s' => 'KC100',
		'kc500_s' => 'KC500',
		'kc700_s' => 'KC700',
		'kc800_s' => 'KC800',
		'kc850_s' => 'KC850',
		'gl600_s' => 'GL600',
		'carmobile_s' => '车载移动检测系统',
		'substation_s' => '变电站红外监测系统',
		'helicopter_s' => '直升机巡检系统',
);
