<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
	'system.home' => '首页',
	'system.login' => '登陆',
	'system.logout' => '退出',
	'system.register' => '注册',

	'company.name' => '广州科易光电技术有限公司',
		
	'menu.index.company' => '走进科易',
	'menu.index.about_us' => '关于我们',
	'menu.index.company.about_keii' => '公司简介',
	'menu.index.company.certificates' => '相关证书',
	
		
	'menu.index.product' => '产品',
	'menu.index.product.kc&gl' => '系列产品',
	'menu.index.product.system' => '系统',
	'products.kc.100' => 'KC100红外热成像仪',
	'products.kc.500' => 'KC500红外热成像仪',
	'products.kc.700' => 'KC700红外热成像仪',
	'products.kc.750' => 'KC750红外热成像仪',
	'products.kc.800' => 'KC800红外热成像仪',
	'products.kc.850' => 'KC850红外热成像仪',
	'products.gl.600' => 'GL600 SF6气体红外检漏仪',
	'products.carmobile' => '车载移动检测系统',
	'products.helicopter' => '直升机巡检系统',
	'products.substation' => '变电站红外监测系统',
	'products.preventive' => '红外热成像预知性检测服务',
	
	'products.kc.100.abbr' => 'KC100',
	'products.kc.500.abbr' => 'KC500',
	'products.kc.700.abbr' => 'KC700',
	'products.kc.750.abbr' => 'KC750',
	'products.kc.800.abbr' => 'KC800',
	'products.kc.850.abbr' => 'KC850',
	'products.gl.600.abbr' => 'GL600',
	'products.carmobile.abbr' => '车载移动检测系统',
	'products.helicopter.abbr' => '直升机巡检系统',
	'products.substation.abbr' => '变电站红外监测系统',
	
	'product.product_list' => '产品列表',
	'product.application' => '产品应用',
	'product.introduction' => '产品介绍',
	'product.parameter' => '产品参数',
	'product.gallery' => '产品图库',
	
	'menu.index.application_gallery' => '案例图库',
	'menu.index.application_gallery.industries' => '行业',
	'menu.index.application_gallery.automation' => '自动化行业',
	'menu.index.application_gallery.building_diagnostics' => '建筑行业',
 	'menu.index.application_gallery.cement&glass' => '水泥和玻璃工业',
	'menu.index.application_gallery.electrical' => '电力行业',
	'menu.index.application_gallery.metallurgy&steel' => '冶金及钢铁工业',
	'menu.index.application_gallery.pulp&paper' => '造纸工业',
	'menu.index.application_gallery.petrochemical' => '石化工业',
	
	'application_gallery.industries' => '行业',
	'application_gallery.automation' => '自动化行业',
	'application_gallery.building_diagnostics' => '建筑行业',
	'application_gallery.cement&glass' => '水泥和玻璃工业',
	'application_gallery.electrical' => '电力行业',
	'application_gallery.metallurgy&steel' => '冶金及钢铁工业',
	'application_gallery.pulp&paper' => '造纸工业',
	'application_gallery.petrochemical' => '石化工业',
	
	'menu.index.application_gallery.applications' => '应用',
	'menu.index.application_gallery.gas_leak_checking' => '气体泄漏检查应用',
	'menu.index.application_gallery.predictive_maintenance' => '预防性检测',
	'menu.index.application_gallery.R&D' => '研发领域应用',
	
	'application_gallery.gas_leak_checking' => '气体泄漏检查应用',
	'application_gallery.predictive_maintenance' => '预防性检测',
	'application_gallery.R&D' => '研发领域应用',
	
	'menu.index.thermography_theory.abbr' => '红外理论',
	'menu.index.thermography_theory' => '红外热像理论',
	'menu.index.technical.terms' => '红外技术名词',
	'menu.index.parameter' => '技术参数',
	'menu.index.field' => '红外热像应用领域',
	'menu.index.IR_camera_history' => '红外热像发展历史',
	'menu.index.IR_camera?' => '什么是热像仪',
	'menu.index.dynamic_IR?' => '什么是动态热像仪',
	'menu.index.choose?' => '如何选择热像仪',
	
	'menu.index.service&support.abbr' => '服务支持',
	'menu.index.service&support' => '服务与支持',
	'menu.index.pre-sales_enquiry' => '售前咨询',
	'menu.index.after-sales_service' => '售后服务',
	'menu.index.technical_support' => '技术支持',
	'menu.index.inspection_service' => '检测服务',
	
	'menu.index.contact' => '联系我们',
	'menu.index.address' => '联系方式',
	'menu.index.guestbook' => '网上留言',
	
	'content.index.application' => '应用',
	'content.index.application.content' => '基于现场应用，提供电站，防火，安防，研发等领域领先的解决方案',
	'content.index.gallery' => '图库',
	'content.index.gallery.content' => 'KEII自主品牌红外热像仪，基于现场应用开发，性能卓越，您的明智首选!',
	'content.index.certificates' => '证书',
	'content.index.certificates.content' => '广州科易公司掌握多项行业专利技术，并通过ISO9001认证，保证产品质量',
	
	
	
);
