<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => '',
  'Delete' => '',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => '',
  'Either "name" or "value" must be specified for CDataColumn.' => '',
  'Home' => '',
  'workstation' => 'Mobile Workstation',
  'gl600'=>'GL600 - Gas Detector',
  'kc100' => 'KC100 - Infrared Camera',
  'kc500' => 'KC500 - Infrared Camera',
  'kc700' => 'KC700 - Infrared Camera',
  'kc750' => 'KC750 - Infrared Camera',
  'kc800' => 'KC800 - Infrared Camera',
  'kc850' => 'KC850 - Infrared Camera',
  'gl600' => 'GL600 - Gas Detector',
  'carmobile' => 'Mobile Mounted Inspection System',
  'substation' => 'IR Inspection System for Substation',
  'helicopter' => 'Helicopter Patrol & Inspection system',
  'workstation_s' => 'Mobile Workstation',
  'gl600_s'=>'GL600 - Gas Detector',
  'kc100_s' => 'KC100 - Infrared Camera',
  'kc500_s' => 'KC500 - Infrared Camera',
  'kc700_s' => 'KC700 - Infrared Camera',
  'kc750_s' => 'KC750 - Infrared Camera',
  'kc800_s' => 'KC800 - Infrared Camera',
  'kc850_s' => 'KC850 - Infrared Camera',
  'gl600_s' => 'GL600 - Gas Detector',
  'carmobile_s' => 'Mobile Mounted Inspection System',
  'substation_s' => 'IR Inspection System for Substation',
  'helicopter_s' => 'Helicopter Patrol & Inspection system',
  'No results found.' => '',
  'Not set' => '',
  'Please specify the "attributes" property.' => '',
  'Please specify the "data" property.' => '',
  'Sort by: ' => '',
  'The "dataProvider" property cannot be empty.' => '',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '',
  'The button type "{type}" is not supported.' => '',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '',
  'The property "itemView" cannot be empty.' => '',
  'The property updateSelector should be defined.' => '',
  'Total 1 result.|Total {count} results.' => '',
  'Update' => '',
  'View' => '',
  '{class} must specify "model" and "attribute" or "name" property values.' => '',
);
