<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'The property updateSelector should be defined.' => '',
  'Are you sure you want to delete this item?' => '确定要删除这条数据吗?',
  'Delete' => '删除',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => '第 {start}-{end} 条, 共 {count} 条.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumn 必须指定 "name" 或 "value" 至少一项.',
  'Home' => '首页',
  'Login' => '登陆',
  'About Keii' => '走进科易',
  'Profile' => '公司简介',
  'Certificate' => '相关证书',
  'Cases'=>'案例图库',
  'Industry' => '行业',
  'Application' => '应用',
  'IR Theory' => '红外理论',
  'Infrared technology' => '红外技术名词',
  'Infrared camera' => '什么是热像仪',
  'Dynamic infrared camera' => '什么是动态热像仪',
  'How to choose?' => '如何选择热像仪',
  'Service' => '服务支持',
  'Sales Inquiries' => '售前咨询',
  'After Sales' => '售后服务',
  'Technical' => '技术支持',
  'Thermography Inspection' => '检测服务',
  'Member' => '会员专区',
  'Contact Us' => '联系我们',
  'Username' => '用户名',
  'Password' => '密码',
  'Logout' => '退出登陆',
  'Remember me next time' => '记住我',
  'Required User' => '需要填写用户',
  'Required Password' => '需要填写密码',
  'Electrical' => '电力行业',
  'Building Diagnostics' => '建筑行业',
  'Cement and Glass' => '水泥和玻璃工业',
  'Metallurgy and steel' => '冶金及钢铁工业',
  'Petrochemical Industry' => '石化工业',
  'Automation' => '自动化行业',
  'Predictive Maintenance' => '预防性检测',
  'Pulp and Paper Industry' => '造纸工业',
  'R&D' => '研发领域应用',
  'Gas Leak Checking' => '气体泄漏检查应用',
  'Corporation' => '公司',
  'Contact Address' => '联系地址',
  'User Register' => '用户注册',
  'Save' => '保存',
  'No results found.' => '没有找到数据.',
  'Not set' => '未设置',
  'Please specify the "attributes" property.' => '请指定 "attributes" 属性.',
  'Please specify the "data" property.' => '请指定 "data" 属性.',
  'Sort by: ' => '排序: ',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" 属性不能为空.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '属性格式 "Name:Type:Label", "Type" 和 "Label" 为可选项.',
  'The button type "{type}" is not supported.' => '按钮类型 "{type}" 不支持。',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '栏位格式 "Name:Type:Label", "Type" 和 "Label" 为可选项.',
  'The property "itemView" cannot be empty.' => '必须指定 "itemView" 属性.',
  'Total 1 result.|Total {count} results.' => '共 {count} 条.',
  'Update' => '更新',
  'View' => '查看',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} 必须给定 "model" 与 "attribute" 或 "name" 属性值.',
  'Product' => '产品介绍',
  'workstation' => '移动红外工作站',
  'kc100' => 'KC100红外热成像仪',
  'kc500' => 'KC500红外热成像仪',
  'kc700' => 'KC700红外热成像仪',
  'kc800' => 'KC800红外热成像仪',
  'kc850' => 'KC850红外热成像仪',
  'gl600' => 'GL600 SF6气体红外检漏仪',
  'carmobile' => '车载移动检测系统',
  'substation' => '变电站红外监测系统',
  'helicopter' => '直升机巡检系统',
  'workstation_s' => '移动红外工作站',
  'kc100_s' => 'KC100',
  'kc500_s' => 'KC500',
  'kc700_s' => 'KC700',
  'kc800_s' => 'KC800',
  'kc850_s' => 'KC850',
  'gl600_s' => 'GL600',
  'carmobile_s' => '车载移动检测系统',
  'substation_s' => '变电站红外监测系统',
  'helicopter_s' => '直升机巡检系统',
);
