<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
	'system.home' => 'Home',
	'system.login' => 'Login',
	'system.logout' => 'Logout',
	'system.register' => 'Register',
	
	'user.information' => 'User Information',		
	'website.keyword' => 'thermal imaging camera, thermal imagers, infrared cameras, IR cameras, thermal cameras, thermography, infrared monitoring systems, IR surveillance systems, thermal surveillance camera, thermal security systems',
		
	'company.name' => 'Guangzhou Keii Electro Optics Technology Co., Ltd',
	
	'user.register' => 'Register',
	'user.information' => 'User information',
	'user.name' => 'Username',
	'user.password' => 'User password',
	'user.email' => 'Email',
	'user.corporation' => 'Corporation',
	'user.contact_number' => 'Phone number',
	'user.contact_address' => 'Contact address',
		
	'menu.index.company' => 'Company',
	'menu.index.about_us' => 'About Us',
	'menu.index.company.about_keii' => 'About Keii',
	'menu.index.company.certificates' => 'Certificates',
		
	'menu.index.product' => 'Products',
	'menu.index.product.kc&gl' => 'KC&GL',
	'menu.index.product.system' => 'System',
	'products.kc.100' => 'KC100 Infrared Camera',
	'products.kc.500' => 'KC500 Infrared Camera',
	'products.kc.700' => 'KC700 Infrared Camera',
	'products.kc.750' => 'KC750 Infrared Camera',
	'products.kc.800' => 'KC800 Infrared Camera',
	'products.kc.850' => 'KC850 Infrared Camera',
	'products.gl.600' => 'GL600 SF6 Gas Detector',
	'products.carmobile' => 'Mobile-mounted Inspection System',
	'products.helicopter' => 'Helicopter Patrol & Inspection System',
	'products.substation' => 'IR Inspection System for Substation',
	'products.preventive' => 'Predictive maintenance service',
	
	'products.kc.100.abbr' => 'KC100',
	'products.kc.500.abbr' => 'KC500',
	'products.kc.700.abbr' => 'KC700',
	'products.kc.750.abbr' => 'KC750',
	'products.kc.800.abbr' => 'KC800',
	'products.kc.850.abbr' => 'KC850',
	'products.gl.600.abbr' => 'GL600',
	'products.carmobile.abbr' => 'Mobile-mounted Inspection ',
	'products.helicopter.abbr' => 'Helicopter Patrol & Inspection ',
	'products.substation.abbr' => 'IR Inspection for Substation',
	#'products.preventive' => 'Predictive maintenance service',
	
	'product.product_list' => 'Product List',
	'product.application' => 'Application',
	'product.introduction' => 'Introduction',
	'product.parameter' => 'Parameter',
	'product.gallery' => 'Gallery',
	
	'menu.index.application_gallery' => 'Application Gallery',
	'menu.index.application_gallery.industries' => 'Industries',
	'menu.index.application_gallery.automation' => 'Automation',
	'menu.index.application_gallery.building_diagnostics' => 'Building Diagnostics',
 	'menu.index.application_gallery.cement&glass' => 'Cement and Glass',
	'menu.index.application_gallery.electrical' => 'Electrical',
	'menu.index.application_gallery.metallurgy&steel' => 'Metallurgy Steel',
	'menu.index.application_gallery.pulp&paper' => 'Pulp and Paper',
	'menu.index.application_gallery.petrochemical' => 'Petrochemical',
	
	'application_gallery.automation' => 'Automation Industry',
	'application_gallery.building_diagnostics' => 'Building Diagnostics',
	'application_gallery.cement&glass' => 'Cement and Glass Industry',
	'application_gallery.electrical' => 'Electrical Industry',
	'application_gallery.metallurgy&steel' => 'Metallurgy and Steel Industry',
	'application_gallery.pulp&paper' => 'Pulp and Paper Industry',
	'application_gallery.petrochemical' => 'Petrochemical',
	
	
	'menu.index.application_gallery.applications' => 'Applications',
	'menu.index.application_gallery.gas_leak_checking' => 'Gas leak checking',
	'menu.index.application_gallery.predictive_maintenance' => 'Predictive maintenance',
	'menu.index.application_gallery.R&D' => 'R&D',
	
	'application_gallery.gas_leak_checking' => 'Gas leak checking',
	'application_gallery.predictive_maintenance' => 'Predictive maintenance',
	'application_gallery.R&D' => 'R&D',
	
	'menu.index.thermography_theory.abbr' => 'Thermography Theory',
	'menu.index.thermography_theory' => 'Thermography',
	'menu.index.technical.terms' => 'Technical terms',
	'menu.index.parameter' => 'Parameter',
	'menu.index.field' => 'Application',
	'menu.index.IR_camera_history' => 'History',
	'menu.index.IR_camera?' => 'What is an IR camera?',
	'menu.index.dynamic_IR?' => 'What is dynamic IR camera?',
	'menu.index.choose?' => 'How to choose an IR camera?',
	
	'menu.index.service&support.abbr' => 'Support',
	'menu.index.service&support' => 'Service',
	'menu.index.pre-sales_enquiry' => 'Pre-sales enquiry',
	'menu.index.after-sales_service' => 'After-sales service',
	'menu.index.technical_support' => 'Technical support',
	'menu.index.inspection_service' => 'Inspection service',
	
	'menu.index.contact' => 'Contact',
	'menu.index.address' => 'Address',
	'menu.index.guestbook' => 'Guest Book',
	
	'content.index.application' => 'Application',
	'content.index.application.content' => 'Solution for substations, firefighting, security, R&D, etc.',
	'content.index.gallery' => 'Gallary',
	'content.index.gallery.content' => 'Proprietary brand of IR cameras and systems',
	'content.index.certificates' => 'Certificates',
	'content.index.certificates.content' => 'Patents, ISO9001 certification, CE certificate',
);
